//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalkToTreatService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BT_AMITTHAKUR\\SQL2017;Initial Catalog=OmnicxStagingV2;Persist Securit" +
            "y Info=True;User ID=sa")]
        public string OmnicxStagingV2ConnectionString {
            get {
                return ((string)(this["OmnicxStagingV2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BT_SHAILENDRAJA\\SQLEXPRESS;Initial Catalog=OmnicxCustomerRaw;Persist " +
            "Security Info=True;User ID=sa")]
        public string OmnicxCustomerRawConnectionString {
            get {
                return ((string)(this["OmnicxCustomerRawConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BT_AMITTHAKUR\\SQL2017;Initial Catalog=OmnicxCustomersRaw;Persist Secu" +
            "rity Info=True;User ID=sa")]
        public string OmnicxCustomersRawConnectionString {
            get {
                return ((string)(this["OmnicxCustomersRawConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BT_AMITTHAKUR\\SQL2017;Initial Catalog=OmnicxStagingV2;Persist Securit" +
            "y Info=True;User ID=sa")]
        public string OmnicxStagingV2ConnectionString1 {
            get {
                return ((string)(this["OmnicxStagingV2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=OmnicxStagingV2;Persist Security Info=True;" +
            "User ID=sa")]
        public string OmnicxStagingV2ConnectionString2 {
            get {
                return ((string)(this["OmnicxStagingV2ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BT_AVISHEKARORA;Initial Catalog=OmnicxStagingV2;Persist Security Info" +
            "=True;User ID=sa")]
        public string OmnicxStagingV2ConnectionString3 {
            get {
                return ((string)(this["OmnicxStagingV2ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BT_AVISHEKARORA;Initial Catalog=OmnicxStagingV2;Persist Security Info" +
            "=True;User ID=sa;Password=axtrum@123")]
        public string OmnicxStagingV2ConnectionString4 {
            get {
                return ((string)(this["OmnicxStagingV2ConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.0.0.7;Initial Catalog=OmnicxMaster;Persist Security Info=True;User" +
            " ID=sa")]
        public string OmnicxMasterConnectionString {
            get {
                return ((string)(this["OmnicxMasterConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.0.0.7\\LOCALDEV;Initial Catalog=OmnicxStagingV2;Persist Security In" +
            "fo=True;User ID=ocxdev")]
        public string OmnicxStagingV2ConnectionString5 {
            get {
                return ((string)(this["OmnicxStagingV2ConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.0.0.7;Initial Catalog=OmnicxStagingV2;Persist Security Info=True;U" +
            "ser ID=sa;Password=WXXLrYKxL2")]
        public string OmnicxStagingV2ConnectionString6 {
            get {
                return ((string)(this["OmnicxStagingV2ConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.0.0.7;Initial Catalog=OmnicxMaster;Persist Security Info=True;User" +
            " ID=ocxdev")]
        public string OmnicxMasterConnectionString1 {
            get {
                return ((string)(this["OmnicxMasterConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BT_AMITTHAKUR\\SQL2017;Initial Catalog=TalkToTreat;Persist Security In" +
            "fo=True;User ID=sa")]
        public string TalktoTreatConnectionString {
            get {
                return ((string)(this["TalktoTreatConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BT_AMITTHAKUR\\SQL2019;Initial Catalog=TalktoTreat;Persist Security In" +
            "fo=True;User ID=sa")]
        public string TalktoTreatConnectionString1 {
            get {
                return ((string)(this["TalktoTreatConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=199.79.62.22;Initial Catalog=TalktoTreat;Persist Security Info=True;U" +
            "ser ID=talktotreat")]
        public string TalktoTreatConnectionString2 {
            get {
                return ((string)(this["TalktoTreatConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Elaa-PC;Initial Catalog=talktotreat;Integrated Security=True")]
        public string talktotreatConnectionString3 {
            get {
                return ((string)(this["talktotreatConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BRICKRED54;Initial Catalog=TalkToTreat;Integrated Security=True")]
        public string TalkToTreatConnectionString4 {
            get {
                return ((string)(this["TalkToTreatConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BRICKRED54;Initial Catalog=TalkToTreat_05aug_2022_AfterDeployee;Integ" +
            "rated Security=True")]
        public string TalkToTreat_05aug_2022_AfterDeployeeConnectionString {
            get {
                return ((string)(this["TalkToTreat_05aug_2022_AfterDeployeeConnectionString"]));
            }
        }
    }
}
